// Turns a captured anomaly bundle into a self-contained offline fidelity-replay
// test. The generated `*.repro.test.ts` re-runs `resolve(locator, snapshot)`
// against the captured `dom.html` and asserts it reproduces the locator_status
// the daemon recorded at capture time (and, when that status was `resolved`,
// that the offline match is the element the snapshot flagged as the target).
//
// This is a determinism guard: it proves the bundle replays offline. It stays
// green today; an agent fixing a locator/resolve regression edits the locator
// algorithm and watches this and the broader locator-robustness suite together.

import { locator_status_of, type AnomalyReport } from "./anomaly.js";
import { type Locator } from "./locator.js";

export type ReproGenerationInput = {
  report: AnomalyReport;
  dom_html: string;
};

/** Build the source of a `*.repro.test.ts` for one anomaly bundle. */
export function generate_repro_test(input: ReproGenerationInput): string {
  const { report, dom_html } = input;
  const locator = report.locator;
  if (locator === undefined) {
    throw new Error(`Anomaly ${report.id} has no locator; cannot generate a replay test.`);
  }

  const status = locator_status_of(report.resolve_result);
  if (status === undefined) {
    throw new Error(`Anomaly ${report.id} has no captured resolve_result.locator_status; cannot assert a replay outcome.`);
  }
  const expect_target = status === "resolved";
  const offline_imports = expect_target
    ? "parse_snapshot_html, find_anomaly_target, install_offline_dom_globals"
    : "parse_snapshot_html, install_offline_dom_globals";

  return `${header(report, status)}
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { resolve, type Locator, type ResolveResult } from "./schema.js";
import { ${offline_imports} } from "./offline-dom.js";

install_offline_dom_globals();

const DOM_HTML = ${template_literal(dom_html)};

const LOCATOR: Locator = ${json_literal(locator)};

describe(${string_literal(`anomaly repro ${report.id}`)}, () => {
  it("offline resolve reproduces the captured locator_status", () => {
    const root = parse_snapshot_html(DOM_HTML);
    const result = resolve(LOCATOR, root as unknown as Document) as ResolveResult & { element?: unknown };

    assert.equal(
      result.locator_status,
      ${string_literal(status)},
      \`offline resolve status \${result.locator_status} != captured ${status}\`,
    );
${expect_target ? target_assertion() : ""}  });
});
`;
}

function target_assertion(): string {
  return `
    const target = find_anomaly_target(root);
    assert.ok(target, "snapshot is missing a data-loupe-target marker");
    assert.equal(result.element, target, "offline resolve did not return the captured target element");
`;
}

function header(report: AnomalyReport, status: string): string {
  const lines = [
    `// Generated by \`loupe anomalies repro ${report.id}\` — offline fidelity-replay guard.`,
    `// Source: ${report.source} | captured ${report.created_at} | locator_status ${status}`,
    `// Summary: ${one_line(report.summary)}`,
  ];
  if (report.expected !== undefined) lines.push(`// Expected: ${one_line(report.expected)}`);
  if (report.actual !== undefined) lines.push(`// Actual:   ${one_line(report.actual)}`);
  return lines.join("\n");
}

function one_line(value: string): string {
  return value.replace(/\s+/g, " ").trim().slice(0, 200);
}

function json_literal(value: Locator): string {
  return JSON.stringify(value, null, 2);
}

function string_literal(value: string): string {
  return JSON.stringify(value);
}

// Snapshot HTML embeds freely except backticks and `${`, which would break the
// template literal; escape both so the generated source parses.
function template_literal(value: string): string {
  return `\`${value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\``;
}
